import { describe, expect, it } from "vitest";
import {
  GENERATED_EXPORTS_PATH,
  GENERATED_ROUTES_PATH,
  PACKAGE_JSON_PATH,
  generateSharedFiles,
  mergePackageJson,
  relativeImport,
} from "../src/domain/codegen.js";
import { mergeManifests, normalizeManifest } from "../src/domain/manifest.js";

const sources = [
  {
    featureSlug: "checkout",
    manifest: normalizeManifest(
      { routes: ["/checkout"], exports: ["CheckoutButton"], deps: ["stripe@^14.0.0"] },
      "checkout",
    ),
  },
  {
    featureSlug: "auth",
    manifest: normalizeManifest(
      { routes: [{ path: "/login", export: "LoginPage" }], exports: ["useSession"], deps: ["zod@^4.0.0"] },
      "auth",
    ),
  },
];

function filesByPath(files: Array<{ path: string; content: string }>) {
  return new Map(files.map((file) => [file.path, file.content]));
}

describe("shared file codegen", () => {
  it("generates a route table with relative lazy imports", () => {
    const generated = generateSharedFiles(mergeManifests(sources), {
      existingPackageJson: null,
      projectName: "shop",
    });
    const routes = filesByPath(generated.files).get(GENERATED_ROUTES_PATH)!;

    expect(routes).toContain(
      `{ path: "/checkout", feature: "checkout", lazy: () => import("../features/checkout/routes") },`,
    );
    expect(routes).toContain(
      `{ path: "/login", feature: "auth", componentExport: "LoginPage", lazy: () => import("../features/auth/routes") },`,
    );
    expect(routes.startsWith("// Generated by VibeHub")).toBe(true);
  });

  it("generates a barrel of declared exports grouped by module", () => {
    const generated = generateSharedFiles(mergeManifests(sources), {
      existingPackageJson: null,
      projectName: "shop",
    });
    const exports = filesByPath(generated.files).get(GENERATED_EXPORTS_PATH)!;
    expect(exports).toContain(`export { useSession } from "../features/auth/index";`);
    expect(exports).toContain(`export { CheckoutButton } from "../features/checkout/index";`);
  });

  it("is byte-identical regardless of the order features merged in", () => {
    const forward = generateSharedFiles(mergeManifests(sources), {
      existingPackageJson: null,
      projectName: "shop",
    });
    const reversed = generateSharedFiles(mergeManifests([...sources].reverse()), {
      existingPackageJson: null,
      projectName: "shop",
    });
    expect(reversed.files).toEqual(forward.files);
  });

  it("produces no output changes when nothing is declared", () => {
    const generated = generateSharedFiles(mergeManifests([]), {
      existingPackageJson: `{\n  "name": "shop",\n  "dependencies": {}\n}\n`,
      projectName: "shop",
    });
    expect(generated.conflicts).toEqual([]);
    // package.json is unchanged, so it is not rewritten.
    expect(generated.files.map((file) => file.path)).not.toContain(PACKAGE_JSON_PATH);
  });

  it("resolves relative import specifiers from the generated directory", () => {
    expect(relativeImport("src/generated", "src/features/cart/routes")).toBe("../features/cart/routes");
    expect(relativeImport("src/generated", "src/generated/helpers")).toBe("./helpers");
    expect(relativeImport("src/generated", "packages/ui/index")).toBe("../../packages/ui/index");
  });
});

describe("package.json dependency merging", () => {
  it("adds manifest deps, sorts them, and leaves other fields alone", () => {
    const existing = `{\n  "name": "shop",\n  "scripts": { "build": "vite build" },\n  "dependencies": { "react": "^19.0.0" }\n}\n`;
    const result = mergePackageJson(existing, mergeManifests(sources), "shop");
    const parsed = JSON.parse(result.content) as Record<string, unknown>;

    expect(result.conflicts).toEqual([]);
    expect(parsed.scripts).toEqual({ build: "vite build" });
    expect(Object.keys(parsed.dependencies as object)).toEqual(["react", "stripe", "zod"]);
  });

  it("creates a package.json when the repo has none", () => {
    const result = mergePackageJson(null, mergeManifests(sources), "shop");
    const parsed = JSON.parse(result.content) as { name: string; dependencies: object };
    expect(parsed.name).toBe("shop");
    expect(parsed.dependencies).toEqual({ stripe: "^14.0.0", zod: "^4.0.0" });
  });

  it("flags a repo pin that disagrees with the manifest rather than overwriting it", () => {
    const existing = `{\n  "dependencies": { "stripe": "^13.0.0" }\n}\n`;
    const result = mergePackageJson(existing, mergeManifests(sources), "shop");
    expect(result.conflicts).toHaveLength(1);
    expect(result.conflicts[0]!.message).toMatch(/pinned to "\^13\.0\.0".*requests "\^14\.0\.0"/);
  });

  it("reports an unparseable package.json instead of clobbering it", () => {
    const result = mergePackageJson("{ not json", mergeManifests(sources), "shop");
    expect(result.changed).toBe(false);
    expect(result.conflicts[0]!.message).toMatch(/could not be parsed/);
  });
});
