/**
 * Deterministic generation of the shared wiring files.
 *
 * Nothing here is heuristic: the same set of merged manifests always produces
 * byte-identical output, independent of merge order. That is what makes it safe
 * for VibeHub to own these files outright instead of asking humans (or agents)
 * to hand-merge them.
 */

import { GENERATED_DIR } from "../lib/paths.js";
import type { ManifestConflict, MergedManifest } from "./manifest.js";

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface CodegenResult {
  files: GeneratedFile[];
  conflicts: ManifestConflict[];
}

const BANNER = [
  "// Generated by VibeHub from the union of all merged feature manifests.",
  "// Do not edit: this file is regenerated on every merge and any manual change",
  "// will be overwritten. Declare routes/exports/deps in your feature manifest.",
].join("\n");

export const GENERATED_ROUTES_PATH = `${GENERATED_DIR}routes.ts`;
export const GENERATED_EXPORTS_PATH = `${GENERATED_DIR}exports.ts`;
export const GENERATED_MANIFEST_PATH = `${GENERATED_DIR}manifest.json`;
export const PACKAGE_JSON_PATH = "package.json";

/** Relative specifier from the generated directory to a repo-relative module. */
export function relativeImport(fromDir: string, toModule: string): string {
  const from = fromDir.split("/").filter(Boolean);
  const to = toModule.split("/").filter(Boolean);
  let shared = 0;
  while (shared < from.length && shared < to.length && from[shared] === to[shared]) shared++;
  const up = from.length - shared;
  const segments = [...Array(up).fill(".."), ...to.slice(shared)];
  const specifier = segments.join("/");
  return specifier.startsWith(".") ? specifier : `./${specifier}`;
}

function generatedDirWithoutTrailingSlash(): string {
  return GENERATED_DIR.replace(/\/$/, "");
}

function renderRoutes(merged: MergedManifest): string {
  const dir = generatedDirWithoutTrailingSlash();
  const lines: string[] = [
    BANNER,
    "",
    "export interface GeneratedRoute {",
    "  /** URL path declared by the owning feature. */",
    "  path: string;",
    "  /** Feature that owns this route. */",
    "  feature: string;",
    "  /** Named export to render, or undefined to use the module default export. */",
    "  componentExport?: string;",
    "  /** Lazy module loader, compatible with React Router's `lazy`. */",
    "  lazy: () => Promise<unknown>;",
    "}",
    "",
    "export const routes: GeneratedRoute[] = [",
  ];

  for (const route of merged.routes) {
    const specifier = relativeImport(dir, route.module);
    const parts = [
      `path: ${JSON.stringify(route.path)}`,
      `feature: ${JSON.stringify(route.featureSlug)}`,
    ];
    if (route.export) parts.push(`componentExport: ${JSON.stringify(route.export)}`);
    parts.push(`lazy: () => import(${JSON.stringify(specifier)})`);
    lines.push(`  { ${parts.join(", ")} },`);
  }

  lines.push("];", "", "export default routes;", "");
  return lines.join("\n");
}

function renderExports(merged: MergedManifest): string {
  const dir = generatedDirWithoutTrailingSlash();
  const byModule = new Map<string, string[]>();
  for (const entry of merged.exports) {
    const specifier = relativeImport(dir, entry.module);
    const names = byModule.get(specifier) ?? [];
    names.push(entry.name);
    byModule.set(specifier, names);
  }

  const lines: string[] = [BANNER, ""];
  if (byModule.size === 0) {
    lines.push("// No merged feature declares shared exports yet.", "export {};", "");
    return lines.join("\n");
  }

  for (const specifier of [...byModule.keys()].sort()) {
    const names = [...new Set(byModule.get(specifier))].sort();
    lines.push(`export { ${names.join(", ")} } from ${JSON.stringify(specifier)};`);
  }
  lines.push("");
  return lines.join("\n");
}

function renderManifestJson(merged: MergedManifest): string {
  const doc = {
    generated_by: "vibehub",
    routes: merged.routes.map((route) => ({
      path: route.path,
      feature: route.featureSlug,
      module: route.module,
      ...(route.export ? { export: route.export } : {}),
    })),
    exports: merged.exports.map((entry) => ({
      name: entry.name,
      feature: entry.featureSlug,
      module: entry.module,
    })),
    dependencies: merged.deps,
  };
  return `${JSON.stringify(doc, null, 2)}\n`;
}

function sortedRecord(record: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(record).sort(([a], [b]) => (a < b ? -1 : 1)));
}

/**
 * Merges manifest dependencies into the repo's package.json. A dependency that
 * the repo already pins to a different range is reported as a conflict rather
 * than silently overwritten.
 */
export function mergePackageJson(
  existing: string | null,
  merged: MergedManifest,
  fallbackName: string,
): { content: string; conflicts: ManifestConflict[]; changed: boolean } {
  const conflicts: ManifestConflict[] = [];
  let doc: Record<string, unknown>;

  if (existing === null || existing.trim() === "") {
    doc = {
      name: fallbackName,
      private: true,
      version: "0.0.0",
      type: "module",
    };
  } else {
    try {
      const parsed: unknown = JSON.parse(existing);
      if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
        throw new Error("package.json is not a JSON object");
      }
      doc = parsed as Record<string, unknown>;
    } catch (error) {
      conflicts.push({
        kind: "dep",
        key: PACKAGE_JSON_PATH,
        message: `Repo package.json could not be parsed, so dependencies cannot be merged: ${
          error instanceof Error ? error.message : String(error)
        }`,
      });
      return { content: existing, conflicts, changed: false };
    }
  }

  const currentDeps: Record<string, string> = {};
  const rawDeps = doc.dependencies;
  if (typeof rawDeps === "object" && rawDeps !== null && !Array.isArray(rawDeps)) {
    for (const [name, value] of Object.entries(rawDeps as Record<string, unknown>)) {
      if (typeof value === "string") currentDeps[name] = value;
    }
  }

  const nextDeps = { ...currentDeps };
  for (const [name, version] of Object.entries(merged.deps)) {
    const current = nextDeps[name];
    if (current === undefined) {
      nextDeps[name] = version === "*" ? "*" : version;
      continue;
    }
    if (current === version || version === "*") continue;
    if (current === "*") {
      nextDeps[name] = version;
      continue;
    }
    conflicts.push({
      kind: "dep",
      key: name,
      message: `Dependency "${name}" is pinned to "${current}" in package.json but a feature manifest requests "${version}". Align the manifest or the repo before merging.`,
    });
  }

  doc.dependencies = sortedRecord(nextDeps);
  const content = `${JSON.stringify(doc, null, 2)}\n`;
  return { content, conflicts, changed: content !== existing };
}

/**
 * Produces every file VibeHub owns, given the merged manifest and the repo's
 * current package.json.
 */
export function generateSharedFiles(
  merged: MergedManifest,
  options: { existingPackageJson: string | null; projectName: string },
): CodegenResult {
  const pkg = mergePackageJson(options.existingPackageJson, merged, options.projectName);

  const files: GeneratedFile[] = [
    { path: GENERATED_ROUTES_PATH, content: renderRoutes(merged) },
    { path: GENERATED_EXPORTS_PATH, content: renderExports(merged) },
    { path: GENERATED_MANIFEST_PATH, content: renderManifestJson(merged) },
  ];
  if (pkg.changed) files.push({ path: PACKAGE_JSON_PATH, content: pkg.content });

  return {
    files: files.sort((a, b) => (a.path < b.path ? -1 : 1)),
    conflicts: [...merged.conflicts, ...pkg.conflicts],
  };
}
