/**
 * Static prompts the team pastes into their own LLM.
 * VibeHub never calls a model — it only validates the JSON that comes back.
 */

/** One-shot from a short idea. No clarifying questions. Plain-language tasks for non-technical readers. */
export const IDEA_SCOPING_PROMPT = `You are helping a non-technical team plan a software project on VibeHub. They will read the task list on a project board — it must read like a product checklist, not an engineering spec.

You will receive ONE idea description. Do NOT ask clarifying questions. Do NOT chat. Make reasonable assumptions and put technical details only in scope_notes (for AI agents — never in title or description).

Rules for features:
1. Break the idea into 4–10 tasks a small team can build in parallel.
2. Each title must be plain English anyone can understand — start with a verb like Add, Build, Fix, or Improve.
   Good: "Add user login", "Let roommates share packing lists", "Send email when a task is done"
   Bad: "Auth module", "Implement Prisma schema", "Components folder", "API layer"
3. Each description explains what the user will be able to do when the task is done — no file paths, frameworks, database tables, or code jargon.
4. depends_on only when one task truly cannot start until another is finished (hard dependency).
5. scope_notes is for agents only: narrow folders/paths this task may touch. Keep it out of title/description.
6. Shared wiring (routers, package.json, app shell) is generated by VibeHub — do not assign those to features.
7. Always return an empty shared_file_warnings array.

Output ONLY this JSON block — no prose before or after:

\`\`\`json
{
  "project_name": "string",
  "features": [
    {
      "id": "lowercase-hyphenated",
      "title": "Add user login",
      "description": "People can sign in and see their own account.",
      "depends_on": ["other-feature-id"],
      "scope_notes": "agent-only paths",
      "manifest": { "routes": [], "exports": [], "deps": [] },
      "test_spec": null
    }
  ],
  "shared_file_warnings": []
}
\`\`\`

Idea:
`;

/** One-shot from an existing repo tree. No clarifying questions. */
export function existingRepoScopingPrompt(input: {
  projectName: string;
  repoUrl: string;
  treeListing: string;
}): string {
  return `You are scoping an EXISTING codebase for VibeHub — parallel AI-agent work with no manual Git merges.

You will receive a file/folder listing. Do NOT ask clarifying questions. Do NOT chat. Infer features from the structure and make reasonable assumptions.

Rules:
1. Produce 4–12 plain-English tasks (Add …, Build …, Fix …) inferred from what the product still needs — NOT from folder names.
2. Titles and descriptions must be understandable by non-technical readers. No file paths or framework jargon in title/description.
3. Never title a task after a directory or file (bad: "Components", "App.tsx"; good: "Add checkout flow").
4. Hard depends_on only. scope_notes may name real paths from the listing for agents.
5. Always return an empty shared_file_warnings array.
6. If the repo looks complete, return an empty features array.

Output ONLY this JSON block — no prose before or after:

\`\`\`json
{
  "project_name": ${JSON.stringify(input.projectName)},
  "features": [
    {
      "id": "lowercase-hyphenated",
      "title": "Add user login",
      "description": "People can sign in and see their own account.",
      "depends_on": [],
      "scope_notes": "paths from the listing",
      "manifest": { "routes": [], "exports": [], "deps": [] },
      "test_spec": null
    }
  ],
  "shared_file_warnings": []
}
\`\`\`

Repo: ${input.repoUrl}

Tree:
${input.treeListing}
`;
}

/** @deprecated use IDEA_SCOPING_PROMPT */
export const SCOPING_PROMPT = IDEA_SCOPING_PROMPT;
